name: Deploy Laravel Project

on:
  push:
    branches:
      - main  # Or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Specify your PHP version

    - name: Install Dependencies
      run: |
        composer install --no-dev --optimize-autoloader

    - name: Run Tests
      run: |
        php artisan test  # Or your preferred testing command

    - name: Build Assets
      run: |
        npm install
        npm run production  # Build front-end assets

    - name: Deploy via FTP
      uses: SamKirkland/ftp-deploy-action@v5
      with:
        local-dir: ./  # Root directory of your Laravel project
        server: $win6054.site4now.net
        username: $raulvdzande-001
        password: $QA06bh89
